### ISSUE TITLE
Elixir 1. guide typo

### ISSUE THREAD

**Issue by geeekgod** [KunalSin9h/website#22]
Hi @KunalSin9h

I really liked your blog series on Elixir, While reading the 1st one I noticed a typo in the installation section.

### Here it is:
Elixir can be installed from the official [installation guild](https://elixir-lang.org/install.html) , what i have seen is for most (if not all) OS have elixir package for elixir.

The installation guide has a typo i.e. `guild`.

Thanks

**Comment by KunalSin9h** [comment]
@thisisrishabh22 thanks
